server:
  port: 8001
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/renshen4322/spring-cloud-examples/     # 配置git仓库的地址
          search-paths: config-repo                             # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: renshen4322                                        # git仓库的账号
          password: gu425006                                    # git仓库的密码
  rabbitmq:
    host: 192.168.1.103
    port: 5672
    username: mark
    password: mark123

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/   ## 注册中心eurka地址


management:
  security:
     enabled: false

